### ISSUE TITLE
The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by PrinceStarLord** [TEAM-PYRO-BOTZ/PYRO-RENAME-BOT#39]
Traceback (most recent call last):
  File "/app/bot.py", line 45, in <module>
    Bot().run()
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/bot.py", line 23, in start
    await super().start()
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect
    await self.session.start()
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Comment by Alihtt** [comment]
Hi
You need to sync your time

If you using windows , you can sync your time with
through win+R... >
timedate.cpl >
Internet time >
time.windows.com >
synchronize

**Comment by PrinceStarLord** [comment]
> Traceback (most recent call last): File "/app/bot.py", line 45, in Bot().run() File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 80, in run run(self.start()) File "/app/.heroku/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/app/bot.py", line 23, in start await super().start() File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 58, in start is_authorized = await self.connect() File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 47, in connect await self.session.start() File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 142, in start raise e File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 109, in start await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT) File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/session/session.py", line 333, in send raise BadMsgNotification(result.error_code) pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

**Comment by PrinceStarLord** [comment]
> Hi You need to sync your time
> 
> If you using windows , you can sync your time with through win+R... > timedate.cpl > Internet time > time.windows.com > synchronize

I'm using linux vps
