### ISSUE TITLE
LOG_CHANNEL error 

### ISSUE THREAD

**Issue by drig0** [TEAM-PYRO-BOTZ/PYRO-RENAME-BOT#52]
Deploy un keyeb

Starting Bot....✨
Traceback (most recent call last):
  File "/workspace/bot.py", line 5, in <module>
    from config import Config
  File "/workspace/config.py", line 27, in <module>
    class Config(object):
  File "/workspace/config.py", line 42, in Config
    LOG_CHANNEL = int(os.environ.get("LOG_CHANNEL"))

**Comment by MrMKN** [comment]
add LOG_CHANNEL id in your variable
